name: CI Pipeline

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest  # Linux runner for Super-Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    name: Build on Windows
    runs-on: windows-latest  # Windows runner for other tasks
    steps:
      - name: Checkout code
        uses: actions/checkout@v
